# docker-compose.yml

services:
  fisica: 
    build:
      context: .
      dockerfile: Dockerfile  
    image: fisica
    container_name: fisica
    restart: unless-stopped
    ports:
      - "8520:8501"